version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3333
    entrypoint: sh -c "npm install && npm run start:dev"
    tty: true
    volumes:
      - ./:/app
    environment:
      NODE_ENV: development